import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import { createVuetify } from 'vuetify'
import {
  VAlert,
  VApp,
  VAppBar,
  VAutocomplete,
  VAvatar,
  VBadge,
  VBtn,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VCol,
  VContainer,
  VDataTable,
  VDialog,
  VDivider,
  VForm,
  VIcon,
  VImg,
  VList,
  VListItem,
  VListSubheader,
  VMain,
  VNavigationDrawer,
  VProgressCircular,
  VRadio,
  VRow,
  VSelect,
  VSkeletonLoader,
  VSpacer,
  VTable,
  VTextField,
  VTextarea,
  VToolbar,
  VToolbarTitle,
  VTooltip,
} from 'vuetify/components'
import { Ripple } from 'vuetify/directives'
import { aliases, mdi } from 'vuetify/iconsets/mdi'

export const vuetify = createVuetify({
  components: {
    VAlert,
    VApp,
    VAppBar,
    VAutocomplete,
    VAvatar,
    VBadge,
    VBtn,
    VCard,
    VCardActions,
    VCardSubtitle,
    VCardText,
    VCardTitle,
    VCheckbox,
    VChip,
    VCol,
    VContainer,
    VDataTable,
    VDialog,
    VDivider,
    VForm,
    VIcon,
    VImg,
    VList,
    VListItem,
    VListSubheader,
    VMain,
    VNavigationDrawer,
    VProgressCircular,
    VRadio,
    VRow,
    VSelect,
    VSkeletonLoader,
    VSpacer,
    VTable,
    VTextField,
    VTextarea,
    VToolbar,
    VToolbarTitle,
    VTooltip,
  },
  directives: {
    Ripple,
  },
  icons: {
    defaultSet: 'mdi',
    aliases,
    sets: {
      mdi,
    },
  },
})
